### ISSUE TITLE
Expose more stack level variables

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/stack-ibm-core-security-services#11]
some suggestions..
- secret_manager_service_plan
- existing_secrets_manager_crn
- enable_platform_logs_metrics

Maybe others?

**Comment by tyao117** [comment]
secret_manager_service_plan is now integrated in. 
enable_platform is enabled by default. 
I suggest having `existing_secrets_manager_crn` out until we get feedback.
We shouldn't put more features in until we get usage.
