### ISSUE TITLE
Review stack variable descriptions

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/stack-ibm-core-security-services#12]
Review stack variable descriptions: https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/blob/main/ibm_catalog.json

Maybe take a look at https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/blob/main/ibm_catalog.json as a reference?

**Comment by SirSpidey** [comment]
closed by #20
