### ISSUE TITLE
Link to public doc is broken

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-ibm-core-security-services#156]
https://cloud.ibm.com/catalog/architecture/deploy-arch-ibm-core-security-svcs-0294f96e-7314-48d1-a710-c08a541b2119-global?kind=terraform&format=stack&version=c72d9380-c3d2-495b-adbe-05b60f8d1e4a-global - the docs link is going to a broken page.

It should be pointing to https://cloud.ibm.com/docs/security-hub?topic=security-hub-core-security-services-pattern

**Comment by ocofaigh** [comment]
Fix coming in https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/pull/157
