### ISSUE TITLE
Prefix set for stack is not uniformly applied across all resources 

### ISSUE THREAD

**Issue by bhakta-ibm** [terraform-ibm-modules/stack-ibm-core-security-services#21]
As you can see the `cssc` is set as the prefix under configure  section. 

![image](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/assets/57999770/b59e4901-263f-4b20-9de9-df7d789ee6a9)

However, when the resources are provisioned, the `cssc` is not set for the event notification resource. Also, it has `base` as prefix which should not be there. 

Moreover, all the security services are using `base-security-services` along with `cssc`. I believe the `base-security-services` is the default prefix for security services, which should be replaced with user provided. 

![image](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/assets/57999770/8f6d262b-b7da-4f17-94b8-9768a6ad628d)

**Comment by ocofaigh** [comment]
Looks like the prefix value isn't being passed to some DAs in the stack definition json
