### ISSUE TITLE
Stack does not deploy latest DA versions

### ISSUE THREAD

**Issue by bhakta-ibm** [terraform-ibm-modules/stack-ibm-core-security-services#22]
Core security services stack 0.0.2 version deploys successfully. Right after its deployed, it has notifications all members has new versions available. Can it be deployed with the latest version of the members?

![image](https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/assets/57999770/3a41a6bd-10ff-487f-851d-5d22d9d5e05e)

**Comment by ocofaigh** [comment]
@bhakta-ibm we are working on some automation to automate this

**Comment by Soaib024** [comment]
For now, we have updated them manually. Should we keep the issue open to track the automation? @ocofaigh @daniel-butler-irl

**Comment by daniel-butler-irl** [comment]
We do have automation for this, it just has not been enabled. We will discuss with the team how often we want to release a new stack version. DAs release quite frequently so probably do not want to release a new stack version quite as fast. Maybe weekly would be frequent enough.

**Comment by ocofaigh** [comment]
We are already tracking the automation internally, so closing this
