### ISSUE TITLE
Update stack to latest Event Notifications DA and handle the support for COS integration

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/stack-ibm-core-security-services#9]
Once https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/157# is merged the DA will by default be integrated with COS which is used for collecting failed events. 
The code allows you to create a COS bucket in an existing COS instance, so lets use the instance that is created by the Observability DA, and use the Key Protect instance created by KMS DA to allow it to create a root key for bucket encryption.

**Comment by ocofaigh** [comment]
This should be good to go now as changes went into https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/releases/tag/v1.4.0

**Comment by tyao117** [comment]
The stack definition uses v1.4.1
https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/blob/main/stack_definition.json#L110

will update the stack to use event_notifications.

**Comment by Soaib024** [comment]
blocked by PR: https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/217

**Comment by Soaib024** [comment]
PR merged - hence closing the issue
